apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-amf-1-config
  labels:
    epc-mode: amf
data:
  amf.yaml: |
    logger:
        file: /var/log/open5gs/amf.log
        #level: debug
        #domain: sbi

    amf:
        sbi:
        - addr: 0.0.0.0
          advertise: {{ .Release.Name }}-amf-1
        ngap:
          dev: {{ .Values.amf1.ngapInt }}
        guami:
          - plmn_id:
              mcc: {{ .Values.amf1.mcc }}
              mnc: {{ .Values.amf1.mnc }}
            amf_id:
              region: 2
              set: 1
        tai:
          - plmn_id:
              mcc: {{ .Values.amf1.mcc }}
              mnc: {{ .Values.amf1.mnc }}
            tac: {{ .Values.amf1.tac }}
        plmn_support:
        - plmn_id:
            mcc: {{ .Values.amf1.mcc }}
            mnc: {{ .Values.amf1.mnc }}
          s_nssai:
          - sst: 1
            sd: 1
        security:
            integrity_order : [ NIA2, NIA1, NIA0 ]
            ciphering_order : [ NEA0, NEA1, NEA2 ]
        network_name:
            full: Open5GS
        amf_name: open5gs-amf1

    nrf:
     sbi:
       name: {{ .Release.Name }}-nrf
